### ISSUE TITLE
Поправка к вызывающему макросу для устранения конфликтов с arclite и тулбарами

### ISSUE THREAD

**Issue by VictorVG** [iyudincev/SizeManager#1]
Получил на forum.ru-board.com в ПМ баг-репорт от **skipik** - в его сборке плагин перехватывал диалоги arclite и не выводились тулбары по F5, F6, F8 и при нажатии Enter:

> Опять вернулась проблема с прогресс-баром, которая связана была со скриптом Size Manager. У меня бар не появляется ни на архивировании, на ни копировании, попробуйте исправить, а я сразу же проверю! 

. Повозился, поправил:

```
-- Макрос назначен на LAltShiftS. Плагин вызывается в реальных файловых
-- панелях и дереве каталогов, навигация работает только в панели плагина.
--
-- (c) VictorVG @ VikSoft.Ru, 2014 - 2015 , (c) Igor Yudincev, 2015
-- История версий:
--
-- v1.0 - первая версия, только звали плагин, навигации в нём ещё не было
-- 02.08.2014, 14:11:44 +0300
-- v1.1 - добавлена навигация из Size Manager.lua by Igor Yudincev.
-- 18.04.2015, 15:00:27 +0300
-- v1.2 - рефакторинг, пытаемся устранить конфликт с ArcLite (баг-репорт skipik)
-- Wed Jun 24 04:05:28 +0300 2015
-- v1.3 - рефакторинг, пытаемся устранить конфликт с F5/F6/F8 (баг-репорт skipik)
-- Thu Jun 25 13:55:50 +0300 2015
-- v1.4 - рефакторинг
-- Thu Jun 25 23:30:20 +0300 2015
-- v1.5 - рефакторинг: вроде окончательный вид, дальше шлифовать только портить
-- Fri Jun 26 00:43:15 +0300 2015
--

local SMId="F36E3C60-C77F-43F2-83C1-8A879DDBBCD7";
local SMMId="F3D9C64A-BC7A-49A5-8FD9-38CAE5A37282";
local DlgId1="E41F6EFF-49DA-40D8-BB50-37D355D812CC";
local DlgId2="5431982E-24CA-4BAC-8831-177300C2405C";

Macro{
area="Shell Tree";
key="LAltShiftS";
flags="NoPluginPanels NoPluginPPanels NoSendKeysToPlugins";
description="Size Manager: run plugin";
  action=function()
    Plugin.Menu(SMId,SMMId)
  end;
}

Macro {
  area="Dialog";
  key="Enter Home End Up Down PgUp PgDn Left Right CtrPgUp CtrPgPgDn";
  flags="NoPluginPanels NoPluginPPanels NoSendKeysToPlugins";
  priority=0;
  description="Size Manager: panel navigation";
  condition=function() return Dlg.Id==(DlgId1 or DlgId2) end;
  action = function()
         Keys("Esc")
         Keys(akey(1))
         Plugin.Call(SMId,0)
  end;
}
```

первый макрос вызовет плагин чтобы не терять время на лазанье по меню, второй управляет навигацией и в его condition стоит проверка что он вызывается именно в диалогах плагина что исключает перехват управления в других местах. Блок if в данном случае срабатывал поздно, а потому проверка была перенесена на более раннюю стадию. Вроде по первым сообщениям проблему удалось устранить - http://forum.ru-board.com/topic.cgi?forum=5&topic=31718&start=6900#10

**P.S.**

Вариант записи flags="NoPluginPanels|NoPluginPPanels|NoSendKeysToPlugins" сомнителен - luamacro_manual.ru.chm :: Стационарные макросы :: 3. Flags:

_"Опциональное поле flags может содержать набор флагов, разделённых пробелами."_

это место я поправил чтобы не нарываться на подводные камни.

**Comment by VictorVG** [comment]
Получен отчёт ( http://forum.ru-board.com/topic.cgi?forum=5&topic=31718&start=6900#17 ) о проверке скрипта v1.5 - им проблема решена : 

> **skipik**
> 
> **Victor_VG**
> Да, проверил получше, пока всё в норме.
> Сам макрос работает, диалоги копирования и архивирования на месте.

**Comment by iyudincev** [comment]
Исправил названия клавиш, залил.

**Comment by VictorVG** [comment]
Спасибо! Думаю инц можем закрыть поскольку тут мы всё сделали что могли.

**P.S.**

_Опечатки возникают как в клавиатуре батарейки садятся - у меня беспроводная A4TEC Padless N7100, а у неё есть такой недостаток и иной раз вылезают непропайки в кварце (ну, это я мигом правлю, не долго).:)_

**Comment by VictorVG** [comment]
Уточнение для condition:

```
-- Макрос назначен на LAltShiftS. Плагин вызывается в реальных файловых
-- панелях и дереве каталогов, навигация работает только в панели плагина.
--
-- (c) VictorVG @ VikSoft.Ru, 2014 - 2015 , (c) Igor Yudincev, 2015
--
-- История версий:
--
-- v1.0 - первая версия, только звали плагин, навигации в нём ещё не было
-- 02.08.2014, 14:11:44 +0300
-- v1.1 - добавлена навигация из Size Manager.lua by Igor Yudincev.
-- 18.04.2015, 15:00:27 +0300
-- v1.2 - рефакторинг, пытаемся устранить конфликт с ArcLite (баг-репорт skipik)
-- Wed Jun 24 04:05:28 +0300 2015
-- v1.3 - рефакторинг, пытаемся устранить конфликт с F5/F6/F8 (баг-репорт skipik)
-- Thu Jun 25 13:55:50 +0300 2015
-- v1.4 - рефакторинг
-- Thu Jun 25 23:30:20 +0300 2015
-- v1.5 - рефакторинг: вроде окончательный вид, дальше шлифовать только портить
-- Fri Jun 26 00:43:15 +0300 2015
-- v1.6 - Fix typo
-- Tue Jun 30 20:30:21 +0300 2015
--

local SMId="F36E3C60-C77F-43F2-83C1-8A879DDBBCD7";
local SMMId="F3D9C64A-BC7A-49A5-8FD9-38CAE5A37282";
local DlgId1="E41F6EFF-49DA-40D8-BB50-37D355D812CC";
local DlgId2="5431982E-24CA-4BAC-8831-177300C2405C";

Macro {
  area="Shell Tree";
  key="LAltShiftS";
  flags="NoPluginPanels NoPluginPPanels NoSendKeysToPlugins";
  description="Size Manager: run plugin";
  action=function()
    Plugin.Menu(SMId,SMMId)
  end;
}

Macro {
  area="Dialog";
  key="Enter Home End Up Down PgUp PgDn Left Right CtrlPgUp CtrlPgDn";
  flags="NoPluginPanels NoPluginPPanels NoSendKeysToPlugins";
  priority=0;
  description="Size Manager: panel navigation";
  condition=function() return (Dlg.Id==DlgId1 or Dlg.Id==DlgId2) end;
  action = function()
    Keys("Esc")
    Keys(akey(1))
    Plugin.Call(SMId,0)
  end;
}
```

Причина - я ляп в логике пропустил: `С==(A or B)` это не  `not (C xor A) or not (C xor B)`. Поправил, скрипт перезалил - Plugin_SizeManager.lua v1.6 (http://www100.zippyshare.com/v/bK0eWm0q/file.html ).

**Comment by iyudincev** [comment]
Обновил.

**Comment by VictorVG** [comment]
Спасибо! Это я в тот день считал сложную логическую схему и с усталости посадил столь не допустимый ляп. :( Теперь инц мы можем смело закрыть поскольку раз новых баг-репортов не поступало, значит мы все обнаруженные ошибки скрипта исправили.
